version: "3"
services:
  console-service:
    container_name: tezos-fullstack-console-backend
    image: tezos-fullstack-console-backend:latest
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 30002:8080
    environment:
      TEZOS_CONSOLE_HTTP_HOST: 0.0.0.0
      TEZOS_CONSOLE_HTTP_PORT: 8080
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_RECEIVER: ${EMAIL_RECEIVER}
    depends_on:
      - tezos-console-db
    command: ["/usr/wait-for-it.sh", "tezos-console-db:5432", "--timeout=90", "--", "java", "-jar", "tezos-console.jar"]

  tezos-console-db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_DB: 'tezos_console'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
